// Copied from https://man.openbsd.org/ssh_config.5 with following script
//
// const dtElements = document.querySelectorAll('dt');
// const dtIds = [];
// for (let dt of dtElements) {
//   if (dt.id) {
//     dtIds.push(dt.id);
//   }
// }
// copy(dtIds);
//
export const sshConfigList = [
    'Host',
    'Match',
    'AddKeysToAgent',
    'AddressFamily',
    'BatchMode',
    'BindAddress',
    'BindInterface',
    'CanonicalDomains',
    'CanonicalizeFallbackLocal',
    'CanonicalizeHostname',
    'CanonicalizeMaxDots',
    'CanonicalizePermittedCNAMEs',
    'CASignatureAlgorithms',
    'CertificateFile',
    'ChannelTimeout',
    'agent-connection',
    'direct-tcpip',
    'forwarded-tcpip',
    'session',
    'tun-connection',
    'x11-connection',
    'CheckHostIP',
    'Ciphers',
    'ClearAllForwardings',
    'Compression',
    'ConnectionAttempts',
    'ConnectTimeout',
    'ControlMaster',
    'ControlPath',
    'ControlPersist',
    'DynamicForward',
    'EnableEscapeCommandline',
    'EnableSSHKeysign',
    'EscapeChar',
    'ExitOnForwardFailure',
    'FingerprintHash',
    'ForkAfterAuthentication',
    'ForwardAgent',
    'ForwardX11',
    'ForwardX11Timeout',
    'ForwardX11Trusted',
    'GatewayPorts',
    'GlobalKnownHostsFile',
    'GSSAPIAuthentication',
    'GSSAPIDelegateCredentials',
    'HashKnownHosts',
    'HostbasedAcceptedAlgorithms',
    'HostbasedAuthentication',
    'HostKeyAlgorithms',
    'HostKeyAlias',
    'Hostname',
    'IdentitiesOnly',
    'IdentityAgent',
    'IdentityFile',
    'IgnoreUnknown',
    'Include',
    'IPQoS',
    'KbdInteractiveAuthentication',
    'KbdInteractiveDevices',
    'KexAlgorithms',
    'KnownHostsCommand',
    'LocalCommand',
    'LocalForward',
    'LogLevel',
    'LogVerbose',
    'MACs',
    'NoHostAuthenticationForLocalhost',
    'NumberOfPasswordPrompts',
    'ObscureKeystrokeTiming',
    'PasswordAuthentication',
    'PermitLocalCommand',
    'PermitRemoteOpen',
    'PKCS11Provider',
    'Port',
    'PreferredAuthentications',
    'ProxyCommand',
    'ProxyJump',
    'ProxyUseFdpass',
    'PubkeyAcceptedAlgorithms',
    'PubkeyAuthentication',
    'RekeyLimit',
    'RemoteCommand',
    'RemoteForward',
    'RequestTTY',
    'RequiredRSASize',
    'RevokedHostKeys',
    'SecurityKeyProvider',
    'SendEnv',
    'ServerAliveCountMax',
    'ServerAliveInterval',
    'SessionType',
    'SetEnv',
    'StdinNull',
    'StreamLocalBindMask',
    'StreamLocalBindUnlink',
    'StrictHostKeyChecking',
    'SyslogFacility',
    'TCPKeepAlive',
    'Tag',
    'Tunnel',
    'TunnelDevice',
    'UpdateHostKeys',
    'User',
    'UserKnownHostsFile',
    'VerifyHostKeyDNS',
    'VersionAddendum',
    'VisualHostKey',
    'XAuthLocation'
];

export const getIterableObjectSshConfigList = () => {
    return sshConfigList.map((str, key) => (
        {
            key: key,
            value: str,
        }
    ))
}